#ifndef BENCHPP_CORE_METRICS_HPP
#define BENCHPP_CORE_METRICS_HPP

#include <string>

namespace benchpp {

enum class Metric {
  HW_CPU_CYCLES,
  SW_CPU_CYCLES,
  CACHE_REFERENCES,
  CACHE_MISSES,
  BRANCH_INSTRUCTIONS,
  BRANCH_MISSES,
  STALLED_CYCLES_FRONTEND,
  STALLED_CYCLES_BACKEND,
  PAGE_FAULTS,
  CONTEXT_SWITCHES,
  CPU_MIGRATIONS
};

[[nodiscard]]
std::string
metric_toStr(const Metric&);

}

#endif /* BENCHPP_CORE_METRICS_HPP */
